# Generated by Django 3.0 on 2021-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_user_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
