# Generated by Django 3.0 on 2021-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_user_signup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
