# Generated by Django 3.0 on 2021-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_user_signup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='usertype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
