# Generated by Django 3.0 on 2021-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0007_auto_20210405_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='flight_image',
            field=models.ImageField(blank=True, null=True, upload_to='flight_images/'),
        ),
    ]
