# Generated by Django 3.0 on 2021-04-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0008_flights_flight_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
