# Generated by Django 3.0 on 2021-04-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0009_delete_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(choices=[('IndiGo', 'IndiGo'), ('Air India', 'Air India'), ('SpiceJet', 'SpiceJet'), ('GoAir', 'GoAir'), ('AirAsia', 'AirAsia'), ('TruJet', 'TruJet'), ('Alliance Air', 'Alliance Air')], max_length=100)),
                ('flight_src', models.CharField(max_length=100)),
                ('flight_dest', models.CharField(max_length=100)),
                ('flight_fare', models.CharField(max_length=100)),
                ('flight_deptime', models.DateTimeField()),
                ('flight_arrtime', models.DateTimeField()),
                ('flight_image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
    ]
