# Generated by Django 3.0 on 2021-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0010_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='flight_dest_image',
            field=models.ImageField(blank=True, null=True, upload_to='flight_images/'),
        ),
    ]
