# Generated by Django 3.0 on 2021-05-01 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0013_auto_20210430_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_arrtime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_deptime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
