# Generated by Django 3.0 on 2021-05-01 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0014_auto_20210501_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_arrtime',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_deptime',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
