# Generated by Django 3.0 on 2021-05-01 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0015_auto_20210501_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(choices=[('The Paradise Inn', 'The Paradise Inn'), ('Hotel deLuxe', 'Hotel deLuxe'), ('Four Seasons', 'Four Seasons'), ('Hi-Way Inn', 'Hi-Way Inn'), ('Candlewood Suites', 'Candlewood Suites'), ('Cute Mountains.', 'Cute Mountains.'), ('Hotel Bliss', 'Hotel Bliss')], max_length=100)),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('hotel_roomfare', models.CharField(max_length=100)),
                ('hotel_chkin', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('hotel_chkout', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('hotel_desc', models.TextField(blank=True, null=True)),
                ('hotel_dest_image', models.ImageField(blank=True, null=True, upload_to='cab_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Cabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_name', models.CharField(choices=[('Fareies', 'Fareies'), ('Fair Fares', 'Fair Fares'), ('Cabme', 'Cabme'), ('Cool Cab', 'Cool Cab'), ('Quick Cab', 'Quick Cab')], max_length=100)),
                ('cab_image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('cab_src', models.CharField(max_length=100)),
                ('cab_dest', models.CharField(max_length=100)),
                ('cab_bookfare', models.CharField(max_length=100)),
                ('cab_deptime', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('cab_arrtime', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('cab_desc', models.TextField(blank=True, null=True)),
                ('cab_dest_image', models.ImageField(blank=True, null=True, upload_to='cab_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
    ]
