# Generated by Django 3.0 on 2021-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0016_cabs_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='cab_image',
            field=models.ImageField(blank=True, null=True, upload_to='cab_images/'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_dest_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
