# Generated by Django 3.0 on 2021-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0022_remove_cart_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
