# Generated by Django 3.0 on 2021-05-02 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0023_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField(default=1)),
                ('hotel_price', models.IntegerField()),
                ('flight_price', models.IntegerField()),
                ('cab_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('cabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Cabs')),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Flights')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
    ]
