# Generated by Django 3.0 on 2021-05-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0025_auto_20210502_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
