# Generated by Django 3.0 on 2021-05-03 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0026_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField(default=1)),
                ('hotel_fare', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
        migrations.CreateModel(
            name='FlightCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField(default=1)),
                ('flight_fare', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
        migrations.CreateModel(
            name='CabCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField(default=1)),
                ('cab_fare', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('cabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Cabs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.User_Signup')),
            ],
        ),
    ]
