# Generated by Django 3.0 on 2021-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0027_cabcart_flightcart_hotelcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabcart',
            old_name='total_price',
            new_name='c_total_price',
        ),
        migrations.RenameField(
            model_name='flightcart',
            old_name='total_price',
            new_name='f_total_price',
        ),
        migrations.RenameField(
            model_name='hotelcart',
            old_name='total_price',
            new_name='h_total_price',
        ),
    ]
