# Generated by Django 3.0 on 2021-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0032_auto_20210510_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
