# Generated by Django 3.0 on 2021-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0033_auto_20210510_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabcart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
